# Generated by Django 5.1.2 on 2025-04-10 11:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Logo', models.ImageField(blank=True, default='images/Software/default.jpg', null=True, upload_to='images/Software/')),
                ('Description', models.CharField(max_length=1000)),
                ('Type', models.CharField(default=' ', max_length=200)),
                ('Categorie', models.CharField(default=' ', max_length=200)),
                ('Supported_Languages', models.CharField(default=' ', max_length=200)),
                ('Platform_System', models.CharField(blank=True, default='', max_length=20)),
                ('Platform_Type', models.CharField(blank=True, default='', max_length=20)),
                ('Special', models.CharField(default=' ', max_length=200)),
                ('Developer', models.CharField(default='', max_length=100)),
                ('Nbr_Rating', models.IntegerField()),
                ('Number_Users', models.IntegerField()),
                ('Rating', models.FloatField()),
                ('Price', models.CharField(blank=True, max_length=50, null=True)),
                ('Version', models.CharField(blank=True, default='1', max_length=20)),
                ('Recommanded_age', models.CharField(blank=True, default='+3', max_length=30)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('DateRelease', models.DateField(blank=True, null=True)),
                ('DateUpdate', models.DateField(blank=True, null=True)),
                ('Finiched', models.BooleanField(default=True)),
                ('Forseal', models.BooleanField(default=False)),
                ('signed', models.BooleanField(default=False)),
                ('Published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('Role', models.SmallIntegerField(choices=[(1, 'User'), (2, 'Worker'), (3, 'Company'), (4, 'Manager'), (5, 'Admin')], default=1)),
                ('ProfilePhoto', models.ImageField(blank=True, default='images/User/default.jpg', null=True, upload_to='images/User/')),
                ('Developer', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_set', related_query_name='user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions_set', related_query_name='user', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Use', models.BooleanField(default=False)),
                ('Creation', models.BooleanField(default=False)),
                ('can_Generate', models.BooleanField(default=False)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(default='', max_length=50)),
                ('Bio', models.CharField(default='', max_length=201)),
                ('Nbr_Rating', models.IntegerField()),
                ('Rating', models.FloatField()),
                ('Nbr_Post', models.IntegerField(default=0)),
                ('User', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User1', to=settings.AUTH_USER_MODEL)),
                ('User2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DomainUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.domaine')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinksProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.CharField(max_length=50)),
                ('URL', models.CharField(max_length=150)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message_Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='', max_length=1000)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('is_user', models.BooleanField(default=False)),
                ('App_Info_persentage', models.FloatField(default=0.0)),
                ('Rec_semularity', models.FloatField(default=0.0)),
                ('Session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=200)),
                ('Date', models.DateTimeField()),
                ('By', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Relation', models.IntegerField(choices=[(1, 'User'), (2, 'Project'), (3, 'User_Software'), (4, 'Job'), (5, 'Software'), (6, 'User_Offer'), (7, 'ChatBot'), (8, 'Message')], default=2)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('Message', models.CharField(blank=True, default='', max_length=100)),
                ('Date_Time', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Notification_to',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opened', models.BooleanField(default=False)),
                ('Notification', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.notification')),
                ('To', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('State', models.CharField(default='_', max_length=50)),
                ('Date', models.DateTimeField(null=True)),
                ('Date_Start', models.DateTimeField(null=True)),
                ('Duration', models.DateTimeField(null=True)),
                ('Budget', models.CharField(default='0', max_length=150)),
                ('LinkF', models.CharField(default='\\', max_length=150)),
                ('LinkChat', models.CharField(default='\\', max_length=150)),
                ('Description', models.CharField(max_length=500)),
                ('Manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job', models.CharField(max_length=50)),
                ('State', models.CharField(default='_', max_length=50)),
                ('Description', models.CharField(default='_', max_length=300)),
                ('Date', models.DateTimeField(default='2000-01-01')),
                ('Payment', models.CharField(max_length=50)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.project')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('Time', models.DateTimeField(null=True)),
                ('count', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill_Rating', models.IntegerField()),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.jobs')),
                ('Skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.skill')),
            ],
        ),
        migrations.CreateModel(
            name='relationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(default='', max_length=50)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Software1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Software1', to='b_serverbas.software')),
                ('Software2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Software2', to='b_serverbas.software')),
            ],
        ),
        migrations.CreateModel(
            name='LinksSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.CharField(max_length=50)),
                ('URL', models.CharField(max_length=150)),
                ('Software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.software')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.ImageField(blank=True, default='images/Software/default.jpg', null=True, upload_to='images/Software/')),
                ('Software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.software')),
            ],
        ),
        migrations.CreateModel(
            name='HistorySoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.FloatField(default=0)),
                ('Save', models.BooleanField(default=0)),
                ('Content', models.CharField(blank=True, default='', max_length=500)),
                ('date', models.DateTimeField(null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.software')),
            ],
        ),
        migrations.CreateModel(
            name='Externt_User_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=50)),
                ('Software', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SoftwareER', to='b_serverbas.software')),
            ],
        ),
        migrations.CreateModel(
            name='Externt_User_Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=50)),
                ('Software', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SoftwareED', to='b_serverbas.software')),
            ],
        ),
        migrations.CreateModel(
            name='App_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=50)),
                ('Software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.software')),
            ],
        ),
        migrations.CreateModel(
            name='Software_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('PlusCnt', models.CharField(blank=True, max_length=100)),
                ('Email', models.CharField(blank=True, max_length=200)),
                ('Contact', models.CharField(blank=True, max_length=200)),
                ('Price', models.CharField(blank=True, max_length=100)),
                ('Software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.software')),
            ],
        ),
        migrations.CreateModel(
            name='Software_recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message_Bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.message_bot')),
                ('Software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.software')),
            ],
        ),
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Domain', to='b_serverbas.domaine')),
                ('SubDomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubDomain', to='b_serverbas.domaine')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.software')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(blank=True, max_length=500)),
                ('Num_Tel', models.CharField(blank=True, max_length=20)),
                ('State', models.SmallIntegerField(choices=[(1, 'Init'), (2, 'In progress'), (3, 'Finished')], default=1)),
                ('Date', models.DateTimeField()),
                ('Software_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.software_offer')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Softwares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.FileField(upload_to='Documents/ChatBot/')),
                ('Specifications', models.FileField(upload_to='Documents/ChatBot/')),
                ('Categorie', models.CharField(blank=True, default='', max_length=100)),
                ('Platform_System', models.CharField(blank=True, default='', max_length=20)),
                ('Platform_Type', models.CharField(blank=True, default='', max_length=20)),
                ('Offer', models.BooleanField(default=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b_serverbas.chatsession')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dev_Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Published', models.DateTimeField(auto_now_add=True)),
                ('Accepted', models.DateTimeField(blank=True, null=True)),
                ('Refused', models.DateTimeField(blank=True, null=True)),
                ('State', models.SmallIntegerField(choices=[(1, 'Init'), (2, 'Accepted'), (3, 'Refused'), (4, 'In progress'), (5, 'Finished')], default=1)),
                ('Comment', models.CharField(blank=True, default='', max_length=500)),
                ('Contact', models.CharField(blank=True, default='', max_length=100)),
                ('Email', models.CharField(blank=True, default='', max_length=100)),
                ('Phone_Number', models.CharField(blank=True, default='', max_length=20)),
                ('Manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b_serverbas.project')),
                ('User_Softwares', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.user_softwares')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profession', models.CharField(max_length=50)),
                ('Education_Level', models.CharField(max_length=50)),
                ('Bio', models.CharField(default='', max_length=201)),
                ('Nbr_Rating', models.IntegerField()),
                ('Rating', models.FloatField()),
                ('Nbr_Post', models.IntegerField(default=0)),
                ('Avalble', models.BooleanField(default=True)),
                ('User', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='software',
            name='By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.worker'),
        ),
        migrations.CreateModel(
            name='RateWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField(default=0, null=True)),
                ('Rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rater', to=settings.AUTH_USER_MODEL)),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Worker', to='b_serverbas.worker')),
            ],
        ),
        migrations.CreateModel(
            name='InterestedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Viewcount', models.IntegerField(default=1)),
                ('Time', models.DateTimeField(null=True)),
                ('Save', models.BooleanField(default=False)),
                ('Is_saved', models.BooleanField(default=False)),
                ('Apply', models.BooleanField(default=False)),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.jobs')),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Apply_For',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Apply', models.DateTimeField()),
                ('Date_Work', models.DateTimeField(null=True)),
                ('State', models.BooleanField(default=False)),
                ('Job', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.jobs')),
                ('Worker', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.worker')),
            ],
        ),
        migrations.CreateModel(
            name='workerMaitrise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill_Rating', models.IntegerField()),
                ('Skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_serverbas.skill')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
