# Generated by Django 5.0.6 on 2025-05-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_serverbas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationships',
            name='Score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='software',
            name='Genres',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='message_bot',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='software',
            name='Type',
            field=models.SmallIntegerField(choices=[(1, 'Paid'), (2, 'Free')], default=2),
        ),
    ]
