# Generated by Django 5.0.6 on 2025-05-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_serverbas', '0002_relationships_score_software_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_softwares',
            name='Genres',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='software',
            name='Description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user_softwares',
            name='Categorie',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_softwares',
            name='Description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user_softwares',
            name='Specifications',
            field=models.FileField(blank=True, null=True, upload_to='Documents/ChatBot/'),
        ),
    ]
